# Generated by Django 6.1 on 2026-08-18 09:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertizer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('company_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('website_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'advertizers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, default=list)),
                ('is_luxury', models.BooleanField(default=True)),
                ('ambiance', models.CharField(choices=[('luxury', 'Luxury'), ('cozy', 'Cozy'), ('modern', 'Modern'), ('vintage', 'Vintage'), ('romantic', 'Romantic'), ('outdoor', 'Outdoor'), ('rooftop', 'Rooftop')], default='luxury', max_length=20)),
                ('price_level', models.CharField(choices=[('₹', 'Budget'), ('₹₹', 'Moderate'), ('₹₹₹', 'Expensive'), ('₹₹₹₹', 'Very Expensive')], default='₹₹₹', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coffee_shops',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(default='funny', max_length=50)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('uploader_name', models.CharField(max_length=200)),
                ('uploader_image', models.CharField(blank=True, max_length=500, null=True)),
                ('coins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.TextField(max_length=5000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('shares', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image_url', models.URLField(max_length=500000)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ad_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='image', max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('brand_color', models.CharField(default='#1877F2', max_length=7)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_action', models.CharField(blank=True, max_length=50, null=True)),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('target_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('target_age_min', models.IntegerField(blank=True, null=True)),
                ('target_age_max', models.IntegerField(blank=True, null=True)),
                ('target_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='vibebookApiApp.advertizer')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='otps_email_aaf0d7_idx'), models.Index(fields=['-created_at'], name='otps_created_701f2d_idx'), models.Index(fields=['expires_at'], name='otps_expires_f6308f_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.TextField(max_length=2000)),
                ('user_profile_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vibebookApiApp.post')),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profile_image', models.CharField(blank=True, max_length=500, null=True)),
                ('cover_image', models.CharField(blank=True, max_length=500, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('coins', models.IntegerField(default=0)),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='received_requests', to='vibebookApiApp.user')),
                ('friends', models.ManyToManyField(blank=True, to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('user_profile_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='vibebookApiApp.user')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewed_stories', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_posts', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='vibebookApiApp.user'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('friend_request_accepted', 'Friend Request Accepted'), ('share', 'Share'), ('mention', 'Mention'), ('vibe_match', 'Vibe Match'), ('coffee_date', 'Coffee Date'), ('meme_like', 'Meme Like')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.comment')),
                ('meme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.meme')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.post')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='vibebookApiApp.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='vibebookApiApp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MemeLike',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_likes', to='vibebookApiApp.meme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_likes', to='vibebookApiApp.user')),
            ],
        ),
        migrations.AddField(
            model_name='meme',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memes', to='vibebookApiApp.user'),
        ),
        migrations.CreateModel(
            name='DateInvite',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('coffee_shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('coffee_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibebookApiApp.coffeeshop')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_date_invites', to='vibebookApiApp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_date_invites', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'date_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DateBooking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('coffee_shop_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.coffeeshop')),
                ('date_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vibebookApiApp.dateinvite')),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_bookings', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'date_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vibebookApiApp.user'),
        ),
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('call_status', models.CharField(choices=[('missed', 'Missed'), ('answered', 'Answered'), ('rejected', 'Rejected'), ('ended', 'Ended')], default='ended', max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('caller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to='vibebookApiApp.user')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'call_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_duration', models.IntegerField(default=0)),
                ('is_skipped', models.BooleanField(default=False)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_records', to='vibebookApiApp.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'ad_impressions',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdDismiss',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('dismiss_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismiss_records', to='vibebookApiApp.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_dismisses', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'ad_dismisses',
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='vibebookApiApp.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'ad_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'user_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status'], name='advertiseme_status_1b1a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_active'], name='advertiseme_is_acti_0d1e64_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['start_date', 'end_date'], name='advertiseme_start_d_fe9acd_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-created_at'], name='advertiseme_created_4b312b_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user'], name='stories_user_id_6205fe_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-created_at'], name='stories_created_caa2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='stories_expires_a4b2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='posts_user_id_05c508_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-timestamp'], name='notificatio_user_id_5d4812_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='messages_sender__89e028_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-timestamp'], name='messages_timesta_865eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memelike',
            unique_together={('user', 'meme')},
        ),
        migrations.AddIndex(
            model_name='dateinvite',
            index=models.Index(fields=['sender', '-created_at'], name='date_invite_sender__7e1cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinvite',
            index=models.Index(fields=['receiver', '-created_at'], name='date_invite_receive_3745b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinvite',
            index=models.Index(fields=['status'], name='date_invite_status_8059ce_idx'),
        ),
        migrations.AddIndex(
            model_name='datebooking',
            index=models.Index(fields=['booked_by', '-created_at'], name='date_bookin_booked__0d194e_idx'),
        ),
        migrations.AddIndex(
            model_name='datebooking',
            index=models.Index(fields=['status'], name='date_bookin_status_470fef_idx'),
        ),
        migrations.AddIndex(
            model_name='datebooking',
            index=models.Index(fields=['date_time'], name='date_bookin_date_ti_54deeb_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_post_id_7ee550_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='comments_created_5a6deb_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['caller'], name='call_histor_caller__08cfac_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['receiver'], name='call_histor_receive_8f1f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['-started_at'], name='call_histor_started_75cb6b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adimpression',
            unique_together={('ad', 'user')},
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user'], name='user_device_user_id_4ec133_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_token'], name='user_device_device__53f0cd_idx'),
        ),
    ]
