# Generated by Django 3.2.25 on 2026-08-10 12:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('call_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], max_length=10)),
                ('call_status', models.CharField(choices=[('missed', 'Missed'), ('answered', 'Answered'), ('rejected', 'Rejected'), ('ended', 'Ended')], default='ended', max_length=10)),
                ('duration', models.IntegerField(default=0)),
                ('channel_name', models.CharField(blank=True, max_length=255, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'call_history',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeDate',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('match_user_name', models.CharField(max_length=255)),
                ('coffee_shop_name', models.CharField(max_length=255)),
                ('coffee_shop_image', models.URLField(max_length=500)),
                ('address', models.TextField()),
                ('distance', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, default=list)),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coffee_dates',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('address', models.TextField()),
                ('distance', models.CharField(max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, default=list)),
                ('is_luxury', models.BooleanField(default=True)),
                ('ambiance', models.CharField(choices=[('luxury', 'Luxury'), ('cozy', 'Cozy'), ('modern', 'Modern'), ('vintage', 'Vintage')], default='luxury', max_length=20)),
                ('price_level', models.CharField(choices=[('$$', 'Moderate'), ('$$$', 'Expensive'), ('$$$$', 'Very Expensive')], default='$$$', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coffee_shops',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.TextField(max_length=2000)),
                ('user_profile_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Meme',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('image_url', models.URLField(max_length=500)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('all', 'All'), ('funny', 'Funny'), ('programming', 'Programming'), ('motivational', 'Motivational'), ('technology', 'Technology'), ('animals', 'Animals'), ('dating', 'Dating'), ('school', 'School'), ('work', 'Work')], default='funny', max_length=20)),
                ('likes', models.IntegerField(default=0)),
                ('comments', models.IntegerField(default=0)),
                ('shares', models.IntegerField(default=0)),
                ('uploader_name', models.CharField(max_length=255)),
                ('uploader_image', models.URLField(blank=True, max_length=500, null=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('coins', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'memes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemeComment',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meme_comments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemeLike',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('coins_earned', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'meme_likes',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File')], default='text', max_length=10)),
                ('is_read', models.BooleanField(default=False)),
                ('is_delivered', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField(max_length=500)),
                ('notification_type', models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('friend_request', 'Friend Request'), ('friend_request_accepted', 'Friend Request Accepted'), ('share', 'Share'), ('mention', 'Mention'), ('vibe_match', 'Vibe Match'), ('coffee_date', 'Coffee Date'), ('meme_like', 'Meme Like')], max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'otps',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('is_online', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('friend_requests', models.ManyToManyField(blank=True, related_name='received_requests', to='vibebookApiApp.User')),
                ('friends', models.ManyToManyField(blank=True, related_name='_vibebookApiApp_user_friends_+', to='vibebookApiApp.User')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='VibeMatchLike',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('is_super_like', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_likes_sent', to='vibebookApiApp.user')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_likes_received', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'vibe_match_likes',
            },
        ),
        migrations.CreateModel(
            name='VibeMatch',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('motivated', 'Motivated'), ('calm', 'Calm'), ('excited', 'Excited'), ('grateful', 'Grateful'), ('confident', 'Confident'), ('adventurous', 'Adventurous'), ('romantic', 'Romantic'), ('fun', 'Fun'), ('chill', 'Chill')], default='happy', max_length=20)),
                ('bio', models.TextField(blank=True, max_length=500, null=True)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('prefer_not_to_say', 'Prefer not to say')], default='prefer_not_to_say', max_length=20)),
                ('looking_for', models.CharField(choices=[('friendship', 'Friendship'), ('dating', 'Dating'), ('relationship', 'Relationship'), ('activityPartner', 'Activity Partner'), ('chat', 'Just Chat'), ('networking', 'Networking')], default='friendship', max_length=20)),
                ('match_percentage', models.FloatField(default=0.0)),
                ('is_online', models.BooleanField(default=False)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('is_liked', models.BooleanField(default=False)),
                ('is_matched', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibe_matches', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'vibe_matches',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'user_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'user_devices',
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('image_url', models.URLField()),
                ('user_profile_image', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='vibebookApiApp.user')),
                ('viewers', models.ManyToManyField(blank=True, related_name='viewed_stories', to='vibebookApiApp.User')),
            ],
            options={
                'db_table': 'stories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('content', models.TextField(max_length=5000)),
                ('images', models.JSONField(blank=True, default=list)),
                ('shares', models.IntegerField(default=0)),
                ('comments_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(blank=True, related_name='liked_posts', to='vibebookApiApp.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'posts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['email'], name='otps_email_aaf0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['-created_at'], name='otps_created_701f2d_idx'),
        ),
        migrations.AddIndex(
            model_name='otp',
            index=models.Index(fields=['expires_at'], name='otps_expires_f6308f_idx'),
        ),
        migrations.AddField(
            model_name='notification',
            name='coffee_date',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.coffeedate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.comment'),
        ),
        migrations.AddField(
            model_name='notification',
            name='meme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.meme'),
        ),
        migrations.AddField(
            model_name='notification',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.post'),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='notification',
            name='vibe_match',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.vibematch'),
        ),
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='memelike',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_likes', to='vibebookApiApp.meme'),
        ),
        migrations.AddField(
            model_name='memelike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_likes', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='memecomment',
            name='meme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_comments', to='vibebookApiApp.meme'),
        ),
        migrations.AddField(
            model_name='memecomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meme_comments', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='meme',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_memes', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_comments', to='vibebookApiApp.User'),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vibebookApiApp.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='coffeedate',
            name='coffee_shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_dates', to='vibebookApiApp.coffeeshop'),
        ),
        migrations.AddField(
            model_name='coffeedate',
            name='match_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coffee_dates', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='caller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_calls', to='vibebookApiApp.user'),
        ),
        migrations.AddField(
            model_name='callhistory',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_calls', to='vibebookApiApp.user'),
        ),
        migrations.AlterUniqueTogether(
            name='vibematchlike',
            unique_together={('from_user', 'to_user')},
        ),
        migrations.AddIndex(
            model_name='vibematch',
            index=models.Index(fields=['user', '-created_at'], name='vibe_matche_user_id_517c33_idx'),
        ),
        migrations.AddIndex(
            model_name='vibematch',
            index=models.Index(fields=['mood'], name='vibe_matche_mood_8961df_idx'),
        ),
        migrations.AddIndex(
            model_name='vibematch',
            index=models.Index(fields=['is_matched'], name='vibe_matche_is_matc_7042fc_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['user'], name='user_device_user_id_4ec133_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_token'], name='user_device_device__53f0cd_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['user'], name='stories_user_id_6205fe_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['-created_at'], name='stories_created_caa2ae_idx'),
        ),
        migrations.AddIndex(
            model_name='story',
            index=models.Index(fields=['expires_at'], name='stories_expires_a4b2b7_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user'], name='posts_user_id_05c508_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-created_at'], name='posts_created_2e2442_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', '-timestamp'], name='notificatio_user_id_5d4812_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['is_read'], name='notificatio_is_read_3f8c44_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type'], name='notificatio_notific_19df93_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'receiver'], name='messages_sender__89e028_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-timestamp'], name='messages_timesta_865eb9_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='messages_is_read_6a69c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='memelike',
            unique_together={('user', 'meme')},
        ),
        migrations.AddIndex(
            model_name='meme',
            index=models.Index(fields=['-created_at'], name='memes_created_90c279_idx'),
        ),
        migrations.AddIndex(
            model_name='meme',
            index=models.Index(fields=['category'], name='memes_categor_a5e805_idx'),
        ),
        migrations.AddIndex(
            model_name='meme',
            index=models.Index(fields=['likes'], name='memes_likes_c216dd_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['post'], name='comments_post_id_7ee550_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['user'], name='comments_user_id_8613ff_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['-created_at'], name='comments_created_5a6deb_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeedate',
            index=models.Index(fields=['match_user', '-created_at'], name='coffee_date_match_u_a0f89a_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeedate',
            index=models.Index(fields=['status'], name='coffee_date_status_77e1ed_idx'),
        ),
        migrations.AddIndex(
            model_name='coffeedate',
            index=models.Index(fields=['date_time'], name='coffee_date_date_ti_ffefe5_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['caller'], name='call_histor_caller__08cfac_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['receiver'], name='call_histor_receive_8f1f1a_idx'),
        ),
        migrations.AddIndex(
            model_name='callhistory',
            index=models.Index(fields=['-started_at'], name='call_histor_started_75cb6b_idx'),
        ),
    ]
