# Generated by Django 3.2.25 on 2026-08-11 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vibebookApiApp', '0002_user_coins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vibematch',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='vibematchlike',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='vibematchlike',
            name='from_user',
        ),
        migrations.RemoveField(
            model_name='vibematchlike',
            name='to_user',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='coffee_date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='vibe_match',
        ),
        migrations.DeleteModel(
            name='CoffeeDate',
        ),
        migrations.DeleteModel(
            name='CoffeeShop',
        ),
        migrations.DeleteModel(
            name='VibeMatch',
        ),
        migrations.DeleteModel(
            name='VibeMatchLike',
        ),
    ]
