# Generated by Django 3.2.25 on 2026-08-11 05:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vibebookApiApp', '0003_auto_20260811_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memecomment',
            name='meme',
        ),
        migrations.RemoveField(
            model_name='memecomment',
            name='user',
        ),
        migrations.RemoveIndex(
            model_name='meme',
            name='memes_created_90c279_idx',
        ),
        migrations.RemoveIndex(
            model_name='meme',
            name='memes_categor_a5e805_idx',
        ),
        migrations.RemoveIndex(
            model_name='meme',
            name='memes_likes_c216dd_idx',
        ),
        migrations.RemoveField(
            model_name='meme',
            name='is_liked',
        ),
        migrations.RemoveField(
            model_name='memelike',
            name='coins_earned',
        ),
        migrations.AlterField(
            model_name='meme',
            name='category',
            field=models.CharField(default='funny', max_length=50),
        ),
        migrations.AlterField(
            model_name='meme',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meme',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='meme',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memes', to='vibebookApiApp.user'),
        ),
        migrations.AlterField(
            model_name='meme',
            name='uploader_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='meme',
            name='uploader_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memelike',
            name='id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='meme',
            table=None,
        ),
        migrations.AlterModelTable(
            name='memelike',
            table=None,
        ),
        migrations.DeleteModel(
            name='MemeComment',
        ),
    ]
