# Generated by Django 3.2.25 on 2026-08-11 09:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('vibebookApiApp', '0004_auto_20260811_1042'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeShop',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('image', models.URLField(blank=True, max_length=500, null=True)),
                ('address', models.TextField()),
                ('city', models.CharField(default='', max_length=100)),
                ('distance', models.CharField(blank=True, max_length=50, null=True)),
                ('rating', models.FloatField(default=0.0)),
                ('review_count', models.IntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('opening_hours', models.JSONField(blank=True, default=list)),
                ('is_luxury', models.BooleanField(default=True)),
                ('ambiance', models.CharField(choices=[('luxury', 'Luxury'), ('cozy', 'Cozy'), ('modern', 'Modern'), ('vintage', 'Vintage'), ('romantic', 'Romantic'), ('outdoor', 'Outdoor'), ('rooftop', 'Rooftop')], default='luxury', max_length=20)),
                ('price_level', models.CharField(choices=[('₹', 'Budget'), ('₹₹', 'Moderate'), ('₹₹₹', 'Expensive'), ('₹₹₹₹', 'Very Expensive')], default='₹₹₹', max_length=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'coffee_shops',
                'ordering': ['-rating', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DateInvite',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('message', models.TextField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('confirmed', 'Confirmed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('coffee_shop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('coffee_shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vibebookApiApp.coffeeshop')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_date_invites', to='vibebookApiApp.user')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_date_invites', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'date_invites',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DateBooking',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('coffee_shop_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending_confirmation', 'Pending Confirmation'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending_confirmation', max_length=20)),
                ('special_requests', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('booked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_bookings', to='vibebookApiApp.user')),
                ('coffee_shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vibebookApiApp.coffeeshop')),
                ('date_invite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='vibebookApiApp.dateinvite')),
            ],
            options={
                'db_table': 'date_bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dateinvite',
            index=models.Index(fields=['sender', '-created_at'], name='date_invite_sender__7e1cbe_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinvite',
            index=models.Index(fields=['receiver', '-created_at'], name='date_invite_receive_3745b0_idx'),
        ),
        migrations.AddIndex(
            model_name='dateinvite',
            index=models.Index(fields=['status'], name='date_invite_status_8059ce_idx'),
        ),
        migrations.AddIndex(
            model_name='datebooking',
            index=models.Index(fields=['booked_by', '-created_at'], name='date_bookin_booked__0d194e_idx'),
        ),
        migrations.AddIndex(
            model_name='datebooking',
            index=models.Index(fields=['status'], name='date_bookin_status_470fef_idx'),
        ),
        migrations.AddIndex(
            model_name='datebooking',
            index=models.Index(fields=['date_time'], name='date_bookin_date_ti_54deeb_idx'),
        ),
    ]
