# Generated by Django 6.1 on 2026-08-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibebookApiApp', '0006_auto_20260812_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, to='vibebookApiApp.user'),
        ),
    ]
