# Generated by Django 6.1 on 2026-08-14 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibebookApiApp', '0007_alter_user_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('image_url', models.URLField(max_length=500)),
                ('video_url', models.URLField(blank=True, max_length=500, null=True)),
                ('ad_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('carousel', 'Carousel')], default='image', max_length=20)),
                ('brand_name', models.CharField(max_length=255)),
                ('brand_logo', models.URLField(blank=True, max_length=500, null=True)),
                ('brand_color', models.CharField(default='#1877F2', max_length=7)),
                ('cta_text', models.CharField(default='Learn More', max_length=50)),
                ('cta_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_action', models.CharField(blank=True, max_length=50, null=True)),
                ('target_audience', models.JSONField(blank=True, default=dict)),
                ('target_gender', models.CharField(blank=True, max_length=20, null=True)),
                ('target_age_min', models.IntegerField(blank=True, null=True)),
                ('target_age_max', models.IntegerField(blank=True, null=True)),
                ('target_location', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('expired', 'Expired')], default='draft', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('impressions', models.IntegerField(default=0)),
                ('clicks', models.IntegerField(default=0)),
                ('ctr', models.FloatField(default=0.0)),
                ('budget', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('advertiser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ads', to='vibebookApiApp.user')),
            ],
            options={
                'db_table': 'advertisements',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdImpression',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('viewed_duration', models.IntegerField(default=0)),
                ('is_skipped', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_impressions', to='vibebookApiApp.user')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impression_records', to='vibebookApiApp.advertisement')),
            ],
            options={
                'db_table': 'ad_impressions',
                'ordering': ['-viewed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdDismiss',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('dismissed_at', models.DateTimeField(auto_now_add=True)),
                ('dismiss_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_dismisses', to='vibebookApiApp.user')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dismiss_records', to='vibebookApiApp.advertisement')),
            ],
            options={
                'db_table': 'ad_dismisses',
                'ordering': ['-dismissed_at'],
            },
        ),
        migrations.CreateModel(
            name='AdClick',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('clicked_at', models.DateTimeField(auto_now_add=True)),
                ('clicked_url', models.URLField(blank=True, max_length=500, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ad_clicks', to='vibebookApiApp.user')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='click_records', to='vibebookApiApp.advertisement')),
            ],
            options={
                'db_table': 'ad_clicks',
                'ordering': ['-clicked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['status'], name='advertiseme_status_1b1a3d_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['is_active'], name='advertiseme_is_acti_0d1e64_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['start_date', 'end_date'], name='advertiseme_start_d_fe9acd_idx'),
        ),
        migrations.AddIndex(
            model_name='advertisement',
            index=models.Index(fields=['-created_at'], name='advertiseme_created_4b312b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='adimpression',
            unique_together={('ad', 'user')},
        ),
    ]
