# Generated by Django 6.1 on 2026-08-17 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibebookApiApp', '0008_advertisement_adimpression_addismiss_adclick_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='image_url',
            field=models.URLField(max_length=500000),
        ),
    ]
